### ISSUE TITLE
Very long sound files

### ISSUE THREAD

**Issue by hambern** [uxms/tts#1]
When I use the plugin to generate a sound file of my blog entry. It takes an huge amount of time and when i get the files it's several hours long. 

I use it like: 

{{ TTS.speak ('sv', post.content)|raw }}

**Comment by uxms** [comment]
Fixed https://github.com/uxms/tts/blob/master/classes/Tts.php#L95

Will be added in next version of plugin

**Comment by uxms** [comment]
Plugin updated on marketplace, also this issue was fixed.
